### ISSUE TITLE
Schedule event, Enabled property value case

### ISSUE THREAD

**Issue by RajasGujarathi** [awsdocs/aws-sam-developer-guide#119]
## Does not work

```yaml
CWSchedule:
   Type: Schedule
   Properties:
     Schedule: 'rate(1 minute)'
     Name: TestSchedule
     Description: test schedule
     Enabled: False
```

## Works

```yaml
CWSchedule:
  Type: Schedule
  Properties:
    Schedule: 'rate(1 minute)'
    Name: TestSchedule
    Description: test schedule
    Enabled: false
```

The property "Enabled" for Type: Schedule accepts "false" instead of "False" (first letter casing). Can someone please verify.
