### ISSUE TITLE
Missing policy in Serverless Policy List

### ISSUE THREAD

**Issue by m17kea** [awsdocs/aws-sam-developer-guide#128]
I believe there is a missing policy in the [serverless policy list](https://github.com/awsdocs/aws-sam-developer-guide/blob/834db2c38a932eaea1f7c6db32064458af44ba29/doc_source/serverless-policy-template-list.md). Once I added the Logging section to my `AWS::Serverless::StateMachine` definition it failed to deploy until added a policy called `CloudWatchLogsFullAccess` as follows:

```
  DistributedTaskRunnerLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: DistributedTaskRunner
      RetentionInDays: 90

  DistributedTaskRunner:
    Type: AWS::Serverless::StateMachine 
    Properties:
      Logging:
        Destinations: 
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DistributedTaskRunnerLog.Arn
        IncludeExecutionData: TRUE
        Level: ALL
      Policies:
        - CloudWatchLogsFullAccess
``` 

This doesn't appear to be documented anywhere so I was unsure whether to just add it to the docs or whether it was a bug from some missing auto-magic.

Happy to submit a PR if that's the way to go here.
