### ISSUE TITLE
What do you mean by "layer-logical-id"

### ISSUE THREAD

**Issue by 6108404** [awsdocs/aws-sam-developer-guide#88]
Can we get some example commands ?  or its same meance Layar-logical-id = layername ?

**Comment by mousedownmike** [comment]
I'm not sure what page you're referring to but in the building layers section, they provide the following example:

```yaml
Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: my_layer
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: python3.6              # Required to have AWS SAM build this layer
```

In that example `MyLayer` is the `layer-logical-id`.  If a build step is required, you should have a build target of `build-MyLayer` in the make file.  

This is explained in the [Building layers](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html) section.
